### ISSUE TITLE
Unable to get image marker orientation in Unreal with multiple markers

### ISSUE THREAD

**Issue by sudhaMR** [google-ar/arcore-unreal-sdk#28]
I am using ARCore's image recognition feature to scan multiple markers and spawn actors based on the marker scanned. It is mostly based on the AugmentedImages example project.

However, I found out that when I scan the 2nd marker and use the "Get Local to World Transform" from the Google ARCoreAugmentedImage object, it gives the transforms of the 1st marker every time. "Get Center" function too seems to return the transforms oriented in the direction of the 1st marker.

For example,
The markers are defined to be like in the image-1.
When scanning these markers I expect the objects spawned to face the direction of the marker, i.e., in -ve axis of x-axis (in red).

[image-1](https://drive.google.com/open?id=1dLm4CHBNdy5H6dZxJYpzoo95ypS27-tP)

However, when I scan the 2nd marker from another position, I expect the character to still face the direction of the marker as shown in image-2 (Since the get transform function should return the transform of the marker scanned?). However, every marker after the 1st marker spawns the character with the orientation of the 1st marker only. "Get Center" and "Get Local to World transform" too returns only the 1st marker's transforms. However, I am able to get the correct index of the image using the "Get Image Index" function.

[image-2](https://drive.google.com/open?id=14CnWPi6HmsQvnaN3FYqa0kdVQKFmg1vn)

**Comment by bopangzz** [comment]
Just to help me better understand the issue, are you saying that when you detect the 2nd marker, its local to world transform has the correction position but use the orientation of the first marker?

Can you attach a screenshot of your blueprint where how you get the local to world transform from the augmented image?

**Comment by sudhaMR** [comment]
![screenshot-2](https://user-images.githubusercontent.com/9298861/42338951-83e9d30a-8059-11e8-88ab-cc0340eb65e8.png)
The Image Object stores the value returned by the Cast To GoogleARCoreAugmentedImage node. I get the local to world transform from this object. At the end of every ForEachLoop iteration, I reset the ImageObject to null so that it should get reassigned in the next loop when a Cast To operation is successful.

I apply an offset of few units in the X axis for the objects spawned by the 2nd marker. The problem is, instead of applying the offset wrt the X-axis of 2nd marker, it applies the offset wrt to the X axis of the 1st marker.

**Comment by bopangzz** [comment]
Hmm, I don't think this is an issue in ARCore plugin as the Augmented Image sample can detect the 2nd maker and get the correct LocalToWorldTransform correctly. If you can create and share a project that could reproduce the issue, I can help take a close look on the blueprint.

**Comment by sudhaMR** [comment]
Here is a [link](https://drive.google.com/file/d/1RtT27j7BgB2GCVO6NAJQvxz4_mNxfgTF/view?usp=sharing) to the project file. It is based on the HelloAR and AugmentedImage examples from the ARCore SDK.

The spawn functions are called in the code of HelloARManager blueprint.

I am not sure if it is returning the correct LocalToWorldTransformation because, if I try to query the Get Center of the scanned image and call Draw Debug Coordinate System, it is always drawn on the center of the first scanned marker.

**Comment by bopangzz** [comment]
@sudhaMR Sorry for the late reply but I found the issue to your problem. It looks like there is a bug in ARCore that the initial detection of the augmented image returns a wrong identity transform. And because how your setup your blueprint, you only uses the transform from the initial detection which causes the problem.

The correct way to handle this is to keep updating the transform of the Actor you want to attach to the image using the LocalToWorldTransform every frame or using the PinComponent function to Pin your Actor with the GoogleARCoreAugmentedImage as the TrackedGometry so that the actor transform will be automatically updated when the transform of the AugmentedImage changes.

I will look into the issue that the initial transform isn't correctly.

**Comment by bopangzz** [comment]
After further investigation, it is actually not a bug. ARCore will detect AugmentedImage when it recongize the image, but it will mark the tracking state as NotTracking before it can get the correct pose of the AugmentedImage. The pose will not be a valid pose if its tracking state is NotTracking. So another way to fix your issue is to only spawn actors when the AugmentedImage object has the Tracking TrackingState.

**Comment by sudhaMR** [comment]
Got it! Thank you @bopangzz . Updating the transform every tick fixed it for me. I will try the other method of spawning only when the Tracking is in TrackingState too.
