### ISSUE TITLE
AcquireCameraImage is always 0 size

### ISSUE THREAD

**Issue by error454** [google-ar/arcore-unreal-sdk#37]
I'm testing on binary UE4 4.20.3 which is using ARCore plugin version 1.2.1.

I'm trying to use `UGoogleARCoreFrameFunctionLibrary::AcquireCameraImage` and noticed that although the call always returns `EGoogleARCoreFunctionStatus::Success`, the width, height and plane count is always 0.

The version of ARCore on the device I'm testing on is `1.5.180910096`. My api versions when building are:
NDK: android-24
SDK: android-27

**Comment by bopangzz** [comment]
Hmm, which phone you are testing on? Have you try to build and run the ComputerVision Sample on that phone?

**Comment by error454** [comment]
> which phone you are testing on?

I'm on the 6p. I can give the CV sample a try and report back.

**Comment by error454** [comment]
After grabbing the 1.2.1 release and trying out the ComputerVision sample, I can say that the results are the same that I'm experiencing.

I actually see the log message get triggered from `GoogleARCoreAPI.cpp`:
`UE_LOG(LogGoogleARCoreAPI, Error, TEXT("AcquireCameraImage failed!"));`

But then `EGoogleARCoreAPIStatus::AR_SUCCESS` is still returned from `AcquireCameraImage` and then the following attempt to create a `UTexture2D` of zero width/height fails spectacularly.

I can't seem to find the source for `ArFrame_acquireCameraImage`? Is there another lib/repo I might be missing? Any other details I can gather for you? I can try out latest 1.5 but it'll take me a half day to get UE4 repo compiled.

**Comment by bopangzz** [comment]
Can you help me get a logcat when running the computer vision sample? This
sounds like a bug that the plugin didn’t handle the error case correctly. I
will look into it.

Also it looks like the acquire image doesn’t work on 6P, which indicate
there is probably some issue in the ARCore SDK as well. Do you happen to
have other ARCore supported phone to test on?

**Comment by error454** [comment]
Here is [a logcat](https://www.dropbox.com/s/2blgmdtj4furzoc/cvlog.txt?dl=0) of the run. I'll see if one of my remote teammates has a device we can try, using the computer vision sample as a test. I just got the 6p as a test device, is it known to have arcore issues? I know it's on the tail end of supported devices but it seemed to be supported.

**Comment by bopangzz** [comment]
After a close look, it looks like the actually failure might be in the ndk camera api.
Which version of Android are those phones on? Also what version of android ndk you are using in Unreal and what is your target/minimal sdk level? Those information can help me identify the issue. Thanks!

**Comment by error454** [comment]
Here is the version info:
6p: 8.1.0
S8+: 8.0.0
Target/minimal: 24
ndk: r12b

**Comment by jimmyryan15** [comment]
I too am seeing this hard crash on Samsung S8. This seems like Hello World and yet even something as basic as this doesn't work? I trust they'll fix it soon or it's time to try a new framework!

**Comment by bopangzz** [comment]
@jimmyryan15 Sorry that you are seeing a crash on S8. Can you create a new issue for that and attach the logcat?

**Comment by jimmyryan15** [comment]
I'll try to get one. To be clear it seems to be the exact same issue as error454 mentioned. Basic build. Any ideas what it could be so far?

**Comment by jimmyryan15** [comment]
Hi, can we get an update when you get a moment please? Is this A) being looked into or B) it WILL be looked into soon or C) realistically this isn't going to be looked into in the next 2 weeks.

Thanks

**Comment by bopangzz** [comment]
Yeah, I am currently looking into this issue. @jimmyryan15 Are you also using the binary version of Unreal 4.20.3 to build the computer vision app? The latest computer vision sample isn't compatible with the GoogleARCore Plugin(1.21) in the binary version of Unreal 4.20.3, due to it uses some of the new API in the latest GoogleARCore plugin.
If you get a chance while I am looking into this, can you try build the Computer Vision Sample using the 
latest GoogleARCore plugin in our forked Unreal Engine repo here: https://github.com/google-ar-unreal/UnrealEngine

**Comment by jimmyryan15** [comment]
Binary version. Please advise if the recommendation is to use the fork (which I guess is A path but not a great one). If that is the case when would everything reconcile so people can just do the normal/binary version.

Thanks

**Comment by bopangzz** [comment]
If you are already working with source code version of Unreal, I would recommend you use our forked version due to it has the latest GoogleARCore plugin.

**Comment by error454** [comment]
I just finished testing the `4.20-arcore` branch, according to the git log it is at arcore 1.5.0. Side-note, the `GoogleARCore.uplugin` still lists the version as 1.4.0. Anyways, it runs successfully on my 6p.

**Comment by bopangzz** [comment]
@error454 Thanks for trying out the 4.20-arcore branch. We missed updating the uplugin file in our last update. We will make sure to update that in our further releases. 

@jimmyryan15 @error454 I was able to repro the issue using the binary version of Unreal 4.20.3 and here is what why it doesn't work in 4.20.3 binary version:
So before GoogleARCore plugin v1.3, the GoogleARCore plugin need to include a header from Android ndk(media/NdkImage.h) which is only available when ndk level is set to 24+. When you build app using a binary version of UE4, it links you app with a precompiled version of GoogleARCore plugin, which is built using android-19, so it doesn't link to those NdkImage functions that ARCore plugin uses to acquire the camera image data. And it it looks like no matter what ndk level you set in your Android SDK settings, UE4 always linked to the precompiled plugin binary. That is why those fucntions in GoogleARCoreCameraImage doesn't work as expected. To me, this seems a bug in Unreal's build system.

This problem doesn't happens in the source code version of Unreal since it always compile the plugin code using the ndk level you set when building the app.

Also in GoogleARCore plugin v1.3 and above, the plugin use dlopen to dynamically load those ndk functions, so future binary version of Unreal(4.21+) shouldn't have this problem anymore.

**Comment by error454** [comment]
> And it it looks like no matter what ndk level you set in your Android SDK settings, UE4 always linked to the precompiled plugin binary. That is why those fucntions in GoogleARCoreCameraImage doesn't work as expected. 

This all makes perfect sense, thanks for digging into this as I can see how it all works now. I think if we wanted to make this work on binary 4.20, we could. It would require removing the ARCore project from the engine plugins and copying to the project folder to use as a project plugin so that it can get compiled. To link a new updated lib, `GoogleARCoreBase.Buildcs` would need to be modified because it has the library dependency path hard-coded:
`RuntimeDependencies.Add("$(EngineDir)/Plugins/Runtime/GoogleARCore/Binaries/ThirdParty/Google/ARCoreImg/" + ExecName);`

Also `GoogleARCoreBase_APL.xml` would need to be modified because it hard-codes the library to copy during deployment:
`<copyFile src="$S(EngineDir)/Source/ThirdParty/GoogleARCore/lib/arm64-v8a/libarcore_sdk_c.so"`

These could be refactored to use relative paths instead of hard-coded engine paths which would allow use as a project plugin. As-is, this will only ever pick up lib changes when the libs at the hard-coded lib paths get re-compiled, and by design, this will never happen in a binary distribution 🙀. I have paths forward now.

**Comment by bopangzz** [comment]
Yeah, you could totally copy the code to a project plugin and build it along with you project. And to your point. And yeah, we should make the path in GoogleARCoreBase.build.cs to use relative path to make it easier to use as a project plugin. 

I don't think you need to modify the path in GoogleARCoreBase_APL.xml, the folder ``$S(EngineDir)/Source/ThirdParty/GoogleARCore`` shouldn't be moved when you move the GoogleARCore plugin. Am I missing anything here?
