### ISSUE TITLE
Augmented images Tracking.

### ISSUE THREAD

**Issue by DasomKong** [google-ar/arcore-unreal-sdk#71]
When AR Images tracked once, the tracking state of AR Images are not changing.

Even tracked images are not in screen view, the return tracking state.

The debugging planes, tracked geometry is at the location which is last tracked.

Somebody know how to judge the images are not in screen after tracked once.

**Comment by elxpyder** [comment]
I am having the same issue, is very frustrating. I have been trying to do some workaround and work in some cases but others don't. One option that work in one case was having a validation, when more than 1 augmented image is detected we stop and start the session, so the augmented image list is cleared. But that won't work in case you can have multiple images at the same time because will reset on every frame. Other option was to use an inverted for each loop and get last image tracked, in this case you can get new images to track, but the bad part is you can't track the previous augmented images until reset. Another way was to get the 0 from the augmented images array, so will only track first and ignore the rest and have a button to manually reset the session. We got specific cases for this where kid of work. But any is bulletproof as having the list updated and having each tracking state updated. In ARKit is working in 4.24 and is a lot better. Hope this help.

**Comment by DasomKong** [comment]
> I am having the same issue, is very frustrating. I have been trying to do some workaround and work in some cases but others don't. One option that work in one case was having a validation, when more than 1 augmented image is detected we stop and start the session, so the augmented image list is cleared. But that won't work in case you can have multiple images at the same time because will reset on every frame. Other option was to use an inverted for each loop and get last image tracked, in this case you can get new images to track, but the bad part is you can't track the previous augmented images until reset. Another way was to get the 0 from the augmented images array, so will only track first and ignore the rest and have a button to manually reset the session. We got specific cases for this where kid of work. But any is bulletproof as having the list updated and having each tracking state updated. In ARKit is working in 4.24 and is a lot better. Hope this help.

The cases you told are the problems I met...
Thank you for reply!
